@echo off
set PERL_SCRIPT_D=%FS_ROOT%\workspace\perl
set XR_PERL_MODULE_DIR=%PERL_SCRIPT_D%\modules
if not exist %FS_CORE%\perl\NUL goto _END
set PERL_DIR=%FS_CORE%\perl
set PERL_VERSION=5.8.9
set PERL_ARCHNAME=MSWin32-x86-multi-thread


if not defined NEWPATH goto _PATH
SET NEWPATH=%NEWPATH%;%PERL_DIR%\%PERL_VERSION%\bin\%PERL_ARCHNAME%;
SET NEWPATH=%NEWPATH%;%PERL_DIR%\%PERL_VERSION%\bin
SET NEWPATH=%NEWPATH%;%PERL_DIR%\site\bin\%PERL_ARCHNAME%;
SET NEWPATH=%NEWPATH%;%PERL_DIR%\site\bin
SET NEWPATH=%NEWPATH%;%PERL_SCRIPT_D%
goto end

:_PATH
SET PATH=%PATH%;%PERL_DIR%\%PERL_VERSION%\bin\%PERL_ARCHNAME%;
SET PATH=%PATH%;%PERL_DIR%\%PERL_VERSION%\bin
SET PATH=%PATH%;%PERL_DIR%\site\bin\%PERL_ARCHNAME%;
SET PATH=%PATH%;%PERL_DIR%\site\bin
SET PATH=%PATH%;%PERL_SCRIPT_D%
goto end

:_donebefore
:end
set PERL_SCRIPT_D=
set PERL_DIR=
set PERL_VERSION=
set PERL_ARCHNAME=
:_END